name: MyFaction
main: MyFaction\MyFaction
version: "0.1-dev#2"
api: ["3.0.0-ALPHA1", "3.0.0-ALPHA2", "3.0.0-ALPHA3", "3.0.0-ALPHA4"]
load: STARTUP
author: SuperPuperSteve
description: Simple factions plugin
softdepend: ["EconomyAPI"]

commands:
 faction:
  aliases: ["f"]
  description: "Faction commands"
 factionadmin:
  aliases: ["fadmin"]
  description: "Faction admin commands"
 myfaction:
  description: "MyFaction plugin configuration"
  permission: myfaction.myfaction
  
permissions:
 myfaction:
  description: "Top permission of MyFaction plugin"
  default: op
  
  children:
   myfaction.myfaction:
    description: "Allows using /myfaction command"
    default: op
