---
# Database type (mysql, sqlite)
# Тип базы данных
type: sqlite

# Database IP
# IP базы данных 
# (mysql)
ip: '127.0.0.1'
# Database username 
# Имя пользователя 
# (mysql)
username: 'username'
# Username's password
# Пароль пользователя
# (mysql)
password: 'password'
# Database name
# Имя базы данных
# (mysql, sqlite)
database: 'username'

# Plugin language (ru/en)
# Язык плагина
language: 'en'

# Use economy (EconomyAPI)?
# Использовать экономику?
use_economy: false

# Do players need to pay money for creating faction?
# Должны ли игроки платить за создание клана?
paid_faction: false

# How much money does player need to pay for faction creation?
# Сколько денег должен платить игрок за создание клана?
faction_cost: 500

# Maximal faction name length
# Макслимальная длина имени клана
faction_length: 15
...